"""
Database initialization - PostgreSQL backend.
Creates all tables (V1.1 + V1.2) and default configuration entries.
No mock data: only system settings are seeded so the user can configure their credentials.
"""

import psycopg2
from config import PG_HOST, PG_PORT, PG_DBNAME, PG_USER, PG_PASSWORD

SCHEMA = """
-- ============================================================
-- V1.1 Tables (existing, converted to PostgreSQL syntax)
-- ============================================================

-- Hot topics collected from platforms
CREATE TABLE IF NOT EXISTS hot_topic (
    id SERIAL PRIMARY KEY,
    platform TEXT NOT NULL DEFAULT '',
    title TEXT NOT NULL,
    author TEXT DEFAULT '',
    publish_time TEXT DEFAULT '',
    likes INTEGER DEFAULT 0,
    comments INTEGER DEFAULT 0,
    favorites INTEGER DEFAULT 0,
    shares INTEGER DEFAULT 0,
    url TEXT DEFAULT '',
    cover TEXT DEFAULT '',
    ai_score REAL DEFAULT 0,
    analysis TEXT DEFAULT '',
    status TEXT DEFAULT 'collected',
    keyword TEXT DEFAULT '',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Scripts generated by AI
CREATE TABLE IF NOT EXISTS script (
    id SERIAL PRIMARY KEY,
    topic_id INTEGER,
    title TEXT NOT NULL,
    hook TEXT DEFAULT '',
    content TEXT DEFAULT '',
    ending TEXT DEFAULT '',
    cover_text TEXT DEFAULT '',
    tags TEXT DEFAULT '',
    version INTEGER DEFAULT 1,
    status TEXT DEFAULT 'draft',
    prompt_tpl TEXT DEFAULT '',
    model_name TEXT DEFAULT '',
    tokens_used INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (topic_id) REFERENCES hot_topic(id) ON DELETE SET NULL
);

-- Video production tasks
CREATE TABLE IF NOT EXISTS video_task (
    id SERIAL PRIMARY KEY,
    script_id INTEGER,
    title TEXT NOT NULL,
    video_style TEXT DEFAULT 'default',
    material_ids TEXT DEFAULT '',
    resolution TEXT DEFAULT '1080x1920',
    fps TEXT DEFAULT '30',
    render_quality TEXT DEFAULT 'high',
    fade_transition TEXT DEFAULT 'true',
    title_overlay TEXT DEFAULT 'false',
    video_engine TEXT DEFAULT 'moviepy',
    narration_prompt TEXT DEFAULT '',
    voice TEXT DEFAULT '',
    voice_rate TEXT DEFAULT '',
    scenes_json TEXT DEFAULT '',
    compose_layout TEXT DEFAULT 'default',
    person_material_id INTEGER,
    bg_material_id INTEGER,
    voice_status TEXT DEFAULT 'pending',
    subtitle_status TEXT DEFAULT 'pending',
    video_status TEXT DEFAULT 'pending',
    export_status TEXT DEFAULT 'pending',
    voice_url TEXT DEFAULT '',
    subtitle_url TEXT DEFAULT '',
    video_path TEXT DEFAULT '',
    output_path TEXT DEFAULT '',
    duration REAL DEFAULT 0,
    error_msg TEXT DEFAULT '',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (script_id) REFERENCES script(id) ON DELETE SET NULL
);

-- Video materials (uploaded images and videos for compositing)
CREATE TABLE IF NOT EXISTS video_material (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    type TEXT NOT NULL DEFAULT 'image',
    file_path TEXT NOT NULL,
    thumbnail TEXT DEFAULT '',
    tags TEXT DEFAULT '',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Customers (V1.2 enhanced with full lifecycle fields)
CREATE TABLE IF NOT EXISTS customer (
    id SERIAL PRIMARY KEY,
    nickname TEXT NOT NULL,
    -- Basic info
    source_video TEXT DEFAULT '',
    wechat TEXT DEFAULT '',
    phone TEXT DEFAULT '',
    tags TEXT DEFAULT '',
    intention TEXT DEFAULT 'low',
    last_follow_time TEXT DEFAULT '',
    remark TEXT DEFAULT '',
    -- V1.2: Extended basic info
    age INTEGER DEFAULT 0,
    occupation TEXT DEFAULT '',
    income TEXT DEFAULT '',
    family_info TEXT DEFAULT '',
    region TEXT DEFAULT '',
    source_channel TEXT DEFAULT '',
    -- V1.2: Customer profile
    personality_type TEXT DEFAULT '',
    risk_preference TEXT DEFAULT '',
    consumption_capacity TEXT DEFAULT '',
    insurance_needs TEXT DEFAULT '',
    family_members TEXT DEFAULT '',
    existing_policies TEXT DEFAULT '',
    future_plans TEXT DEFAULT '',
    -- V1.2: Lifecycle
    lifecycle_stage TEXT DEFAULT 'new',
    -- V1.2: Important dates for reminders
    birthday TEXT DEFAULT '',
    policy_expiry_date TEXT DEFAULT '',
    -- V1.2: Assignment
    assigned_agent TEXT DEFAULT '',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Lead pool (进线线索，未转客户前)
CREATE TABLE IF NOT EXISTS lead (
    id SERIAL PRIMARY KEY,
    nickname TEXT NOT NULL,
    phone TEXT DEFAULT '',
    wechat TEXT DEFAULT '',
    source TEXT NOT NULL DEFAULT 'manual',
    related_content TEXT DEFAULT '',
    preferred_time TEXT DEFAULT '',
    remark TEXT DEFAULT '',
    status TEXT NOT NULL DEFAULT 'pending_contact',
    customer_id INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (customer_id) REFERENCES customer(id) ON DELETE SET NULL
);

-- Follow-up records
CREATE TABLE IF NOT EXISTS follow_record (
    id SERIAL PRIMARY KEY,
    customer_id INTEGER NOT NULL,
    content TEXT NOT NULL,
    follow_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    method TEXT DEFAULT '',
    deal_intention TEXT DEFAULT '',
    next_time TEXT DEFAULT '',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (customer_id) REFERENCES customer(id) ON DELETE CASCADE
);

-- Publish tasks
CREATE TABLE IF NOT EXISTS publish_task (
    id SERIAL PRIMARY KEY,
    video_task_id INTEGER,
    title TEXT DEFAULT '',
    description TEXT DEFAULT '',
    cover_text TEXT DEFAULT '',
    tags TEXT DEFAULT '',
    platform TEXT DEFAULT '',
    scheduled_time TEXT DEFAULT '',
    status TEXT DEFAULT 'pending',
    publish_url TEXT DEFAULT '',
    error_msg TEXT DEFAULT '',
    published_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (video_task_id) REFERENCES video_task(id) ON DELETE SET NULL
);

-- System settings (grouped, with field types for dynamic UI rendering)
CREATE TABLE IF NOT EXISTS system_setting (
    id SERIAL PRIMARY KEY,
    category TEXT NOT NULL,
    key TEXT NOT NULL,
    value TEXT DEFAULT '',
    label TEXT DEFAULT '',
    description TEXT DEFAULT '',
    field_type TEXT DEFAULT 'text',
    options TEXT DEFAULT NULL,
    sort_order INTEGER DEFAULT 0,
    UNIQUE(category, key)
);

-- User-defined / extended ops platforms (collector + publish)
CREATE TABLE IF NOT EXISTS ops_platform (
    id SERIAL PRIMARY KEY,
    key TEXT NOT NULL UNIQUE,
    label TEXT NOT NULL,
    color TEXT DEFAULT 'blue',
    description TEXT DEFAULT '',
    priority INTEGER DEFAULT 100,
    cookie_domain TEXT DEFAULT '',
    creator_url TEXT DEFAULT '',
    search_url_template TEXT DEFAULT '',
    enable_collector BOOLEAN DEFAULT TRUE,
    enable_publish BOOLEAN DEFAULT TRUE,
    builtin BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 自定义 AI 大模型厂商（卡片可添加）
CREATE TABLE IF NOT EXISTS ai_llm_provider (
    id SERIAL PRIMARY KEY,
    key TEXT NOT NULL UNIQUE,
    label TEXT NOT NULL,
    description TEXT DEFAULT '',
    color TEXT DEFAULT 'blue',
    auth_type TEXT DEFAULT 'api_key',
    default_base_url TEXT DEFAULT '',
    default_model TEXT DEFAULT '',
    model_hint TEXT DEFAULT '',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- V1.2 New Tables
-- ============================================================

-- AI Reminder system (customer-focused)
CREATE TABLE IF NOT EXISTS reminder (
    id SERIAL PRIMARY KEY,
    customer_id INTEGER,
    type TEXT NOT NULL DEFAULT 'general',
    title TEXT NOT NULL,
    content TEXT DEFAULT '',
    remind_date DATE,
    status TEXT DEFAULT 'pending',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (customer_id) REFERENCES customer(id) ON DELETE CASCADE
);

-- AI Customer analysis
CREATE TABLE IF NOT EXISTS customer_analysis (
    id SERIAL PRIMARY KEY,
    customer_id INTEGER NOT NULL,
    deal_probability REAL DEFAULT 0,
    focus_points TEXT DEFAULT '',
    risk_assessment TEXT DEFAULT '',
    recommended_products TEXT DEFAULT '',
    next_step TEXT DEFAULT '',
    ai_analysis TEXT DEFAULT '',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (customer_id) REFERENCES customer(id) ON DELETE CASCADE
);

-- AI Knowledge Base items
CREATE TABLE IF NOT EXISTS knowledge_item (
    id SERIAL PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT DEFAULT '',
    source_type TEXT DEFAULT 'note',
    category TEXT DEFAULT '',
    tags TEXT DEFAULT '',
    summary TEXT DEFAULT '',
    ai_analysis TEXT DEFAULT '',
    related_ids TEXT DEFAULT '',
    source_url TEXT DEFAULT '',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Stock watchlist (self-selected stocks)
CREATE TABLE IF NOT EXISTS stock_watchlist (
    id SERIAL PRIMARY KEY,
    stock_code TEXT NOT NULL,
    stock_name TEXT DEFAULT '',
    list_type TEXT DEFAULT 'watch',
    buy_price REAL DEFAULT 0,
    current_price REAL DEFAULT 0,
    quantity INTEGER DEFAULT 0,
    notes TEXT DEFAULT '',
    added_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Stock trading strategies (AI-powered)
CREATE TABLE IF NOT EXISTS stock_strategy (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT DEFAULT '',
    strategy_type TEXT DEFAULT 'trend',
    rules_json TEXT DEFAULT '',
    score REAL DEFAULT 0,
    hit_rate REAL DEFAULT 0,
    total_trades INTEGER DEFAULT 0,
    winning_trades INTEGER DEFAULT 0,
    status TEXT DEFAULT 'active',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Stock screening results
CREATE TABLE IF NOT EXISTS stock_screening (
    id SERIAL PRIMARY KEY,
    name TEXT DEFAULT '',
    conditions_json TEXT DEFAULT '',
    results_json TEXT DEFAULT '',
    status TEXT DEFAULT 'completed',
    message TEXT DEFAULT '',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- AI / 手动复盘记录
CREATE TABLE IF NOT EXISTS stock_review (
    id SERIAL PRIMARY KEY,
    title TEXT DEFAULT '',
    input_text TEXT DEFAULT '',
    summary TEXT DEFAULT '',
    result_json TEXT DEFAULT '',
    tone TEXT DEFAULT 'gray',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 全市场 A 股（夜间同步，新股自动加入）
CREATE TABLE IF NOT EXISTS stock_universe (
    id SERIAL PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    name TEXT DEFAULT '',
    market TEXT DEFAULT '',
    board TEXT DEFAULT '',
    price REAL,
    pct_chg REAL,
    volume REAL,
    amount REAL,
    turnover REAL,
    is_active BOOLEAN DEFAULT TRUE,
    source TEXT DEFAULT 'akshare',
    refreshed_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- AI Agent center
CREATE TABLE IF NOT EXISTS ai_agent (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    agent_type TEXT DEFAULT 'content',
    description TEXT DEFAULT '',
    config_json TEXT DEFAULT '',
    system_prompt TEXT DEFAULT '',
    last_result TEXT DEFAULT '',
    status TEXT DEFAULT 'idle',
    last_run TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Workflow system
CREATE TABLE IF NOT EXISTS workflow (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    workflow_type TEXT DEFAULT 'customer',
    steps_json TEXT DEFAULT '',
    status TEXT DEFAULT 'draft',
    current_step INTEGER DEFAULT 0,
    related_id INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 股票情报：当日财经资讯 + 股市简报 + AI 分析
CREATE TABLE IF NOT EXISTS stock_daily_briefing (
    id SERIAL PRIMARY KEY,
    brief_date DATE NOT NULL UNIQUE,
    news_json TEXT DEFAULT '[]',
    brief_md TEXT DEFAULT '',
    ai_analysis_md TEXT DEFAULT '',
    source_message TEXT DEFAULT '',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 桌宠问答：向量分片（embedding 存 JSON 浮点数组，兼容无 pgvector 环境）
CREATE TABLE IF NOT EXISTS rag_chunk (
    id SERIAL PRIMARY KEY,
    source_type TEXT NOT NULL,
    source_id INTEGER NOT NULL,
    chunk_index INTEGER DEFAULT 0,
    title TEXT DEFAULT '',
    content TEXT DEFAULT '',
    meta_json TEXT DEFAULT '',
    embedding_json TEXT DEFAULT '',
    embedding_model TEXT DEFAULT '',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (source_type, source_id, chunk_index)
);

CREATE TABLE IF NOT EXISTS pet_chat_session (
    id SERIAL PRIMARY KEY,
    title TEXT DEFAULT '',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pet_chat_message (
    id SERIAL PRIMARY KEY,
    session_id INTEGER NOT NULL REFERENCES pet_chat_session(id) ON DELETE CASCADE,
    role TEXT NOT NULL,
    content TEXT DEFAULT '',
    meta_json TEXT DEFAULT '',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Script V1.2 enhancements (columns added via migration)
-- Added as separate ALTER for existing tables
"""


# Default configuration entries - the user fills in their own credentials
DEFAULT_SETTINGS = [
    # ---- AI / LLM（按厂商分卡片；共用参数在 ai）----
    ('ai_zhipu', 'enabled', 'false', '启用智谱',
     '开启后作为当前大模型；建议只启用一家', 'select', '["true","false"]', 1),
    ('ai_zhipu', 'api_key', '', 'API Key', '智谱开放平台 API Key', 'password', None, 2),
    ('ai_zhipu', 'base_url', 'https://open.bigmodel.cn/api/paas/v4', 'API Base URL', '一般无需修改', 'text', None, 3),
    ('ai_zhipu', 'model', 'glm-4-flash', '模型名称', '如 glm-4-flash、glm-4', 'text', None, 4),

    ('ai_volcano', 'enabled', 'false', '启用火山引擎',
     '方舟豆包；模型名称填推理接入点 ID（ep-开头）', 'select', '["true","false"]', 1),
    ('ai_volcano', 'api_key', '', 'API Key', '方舟 ARK_API_KEY', 'password', None, 2),
    ('ai_volcano', 'base_url', 'https://ark.cn-beijing.volces.com/api/v3', 'API Base URL', '一般无需修改', 'text', None, 3),
    ('ai_volcano', 'model', '', '推理接入点 ID', '控制台创建后形如 ep-xxxxxxxx', 'text', None, 4),

    ('ai_qwen', 'enabled', 'false', '启用通义千问',
     '阿里云 DashScope', 'select', '["true","false"]', 1),
    ('ai_qwen', 'api_key', '', 'API Key', 'DashScope API Key', 'password', None, 2),
    ('ai_qwen', 'base_url', 'https://dashscope.aliyuncs.com/compatible-mode/v1', 'API Base URL', '一般无需修改', 'text', None, 3),
    ('ai_qwen', 'model', 'qwen-plus', '模型名称', '如 qwen-plus、qwen-turbo', 'text', None, 4),

    ('ai_deepseek', 'enabled', 'false', '启用 DeepSeek',
     '深度求索', 'select', '["true","false"]', 1),
    ('ai_deepseek', 'api_key', '', 'API Key', 'DeepSeek API Key', 'password', None, 2),
    ('ai_deepseek', 'base_url', 'https://api.deepseek.com/v1', 'API Base URL', '一般无需修改', 'text', None, 3),
    ('ai_deepseek', 'model', 'deepseek-chat', '模型名称', '如 deepseek-chat', 'text', None, 4),

    ('ai_moonshot', 'enabled', 'false', '启用 Moonshot',
     '月之暗面 Kimi', 'select', '["true","false"]', 1),
    ('ai_moonshot', 'api_key', '', 'API Key', 'Moonshot API Key', 'password', None, 2),
    ('ai_moonshot', 'base_url', 'https://api.moonshot.cn/v1', 'API Base URL', '一般无需修改', 'text', None, 3),
    ('ai_moonshot', 'model', 'moonshot-v1-8k', '模型名称', '如 moonshot-v1-8k', 'text', None, 4),

    ('ai_openai', 'enabled', 'false', '启用 OpenAI / ChatGPT',
     '官方 GPT：使用 platform.openai.com 的 API Key（sk-）', 'select', '["true","false"]', 1),
    ('ai_openai', 'api_key', '', 'API Key', 'sk- 开头；不是 ChatGPT 登录密码', 'password', None, 2),
    ('ai_openai', 'base_url', 'https://api.openai.com/v1', 'API Base URL', '官方地址；中转可改', 'text', None, 3),
    ('ai_openai', 'model', 'gpt-4o-mini', '模型名称', '如 gpt-4o-mini、gpt-4o', 'text', None, 4),

    ('ai', 'temperature', '0.7', '创意温度', '0-1，越高越有创意（所有厂商共用）', 'text', None, 1),
    ('ai', 'max_tokens', '2000', '最大Token数', '单次生成最大长度（所有厂商共用）', 'text', None, 2),
    ('ai', 'default_audience', '20-80岁泛流量用户，口播易懂，强共鸣强分享，适合视频号/抖音/小红书', '默认目标受众', '泛流量全年龄段', 'text', None, 3),
    ('ai', 'default_tone', 'casual', '默认文案语气', '', 'select',
     '["professional","casual","passionate","humorous","serious","friendly"]', 4),

    # ---- Collector: Douyin ----
    ('collector_douyin', 'enabled', 'false', '启用抖音采集',
     '高风险：自动化/Cookie 采集易触发平台风控导致封号。推荐用「全网热榜」选题；仅实验时开启。',
     'select', '["true","false"]', 1),
    ('collector_douyin', 'cookies', '', '抖音 Cookies',
     '【高风险·不推荐】登录态采集可能封号。浏览器打开 douyin.com → F12 → Network → 复制 Cookie',
     'textarea', None, 2),
    ('collector_douyin', 'keywords', '养老金,家庭保障,保险避坑,理赔案例,职场内耗,育儿焦虑,健康养生,中年危机,防骗防坑,人情世故', '采集关键词',
     '逗号分隔，泛流量+保险热点', 'text', None, 3),

    # ---- Collector: Xiaohongshu ----
    ('collector_xiaohongshu', 'enabled', 'false', '启用小红书采集',
     '高风险：自动化/Cookie 采集易触发平台风控导致封号。推荐用「全网热榜」选题；仅实验时开启。',
     'select', '["true","false"]', 1),
    ('collector_xiaohongshu', 'cookies', '', '小红书 Cookies',
     '【高风险·不推荐】登录态采集可能封号。浏览器打开 xiaohongshu.com → F12 → Network → 复制 Cookie',
     'textarea', None, 2),
    ('collector_xiaohongshu', 'keywords', '家庭保障,保险避坑,宝妈理财,重疾险,医保报销,情感共鸣,生活智慧', '采集关键词', '逗号分隔', 'text', None, 3),

    # ---- Collector: Shipinhao (视频号) ----
    ('collector_shipinhao', 'enabled', 'false', '启用视频号采集',
     '视频号无公开网页搜索，此开关预留；选题请用全网热榜。', 'select', '["true","false"]', 1),
    ('collector_shipinhao', 'cookies', '', '视频号 Cookies',
     '一般无需配置。浏览器打开 channels.weixin.qq.com → F12 → 复制 Cookie', 'textarea', None, 2),
    ('collector_shipinhao', 'keywords', '养老金,保险避坑,理赔,家庭责任,健康预警,退休生活', '采集关键词', '逗号分隔', 'text', None, 3),

    # ---- TTS (配音) ----
    ('tts', 'provider', 'edge', 'TTS 服务商', '', 'select',
     '["edge","azure","volcano"]', 1),
    ('tts', 'api_key', '', 'TTS API Key',
     'Edge TTS 免费，无需填写；Azure/火山引擎需填写', 'password', None, 2),
    ('tts', 'voice', 'zh-CN-YunxiNeural', '语音角色',
     '可在创建视频时单独选择，也可在此设置全局默认（仅列出 Edge TTS 仍可用的音色）', 'select',
     '["zh-CN-YunxiNeural","zh-CN-XiaoxiaoNeural","zh-CN-YunyangNeural","zh-CN-XiaoyiNeural","zh-CN-YunjianNeural","zh-CN-YunxiaNeural","zh-CN-liaoning-XiaobeiNeural","zh-CN-shaanxi-XiaoniNeural"]', 3),
    ('tts', 'rate', '+0%', '语速', '如 +10%, -5%', 'text', None, 4),
    ('tts', 'volume', '+0%', '音量', '如 +0%', 'text', None, 5),

    # ---- Video Production ----
    ('video', 'ffmpeg_path', 'ffmpeg', 'FFmpeg 路径',
     '系统已安装则填 ffmpeg，否则填完整路径。MoviePy 引擎自带 FFmpeg，此项主要用于 ffprobe 和 FFmpeg 回退。', 'text', None, 1),
    ('video', 'image_source', 'local', '素材图片来源',
     'local=本地目录, pexels=Pexels API', 'select', '["local","pexels"]', 2),
    ('video', 'image_dir', '', '本地素材目录',
     '存放背景图片的文件夹路径', 'text', None, 3),
    ('video', 'pexels_api_key', '', 'Pexels API Key',
     '免费申请: pexels.com/api', 'password', None, 4),
    ('video', 'output_dir', 'outputs', '输出目录', '视频文件输出路径', 'text', None, 5),
    ('video', 'default_resolution', '1080x1920', '默认分辨率',
     '新建视频任务时的默认值，可在创建任务时修改', 'select', '["1080x1920","1920x1080","720x1280"]', 6),
    ('video', 'default_fps', '30', '默认帧率', '新建视频任务时的默认值', 'text', None, 7),
    ('video', 'default_render_quality', 'high', '默认渲染质量',
     'high=高质量(慢) / medium=中等(较快) / preview=预览(最快)', 'select', '["high","medium","preview"]', 8),
    ('video', 'default_video_engine', 'moviepy', '默认合成引擎',
     'moviepy=高质量(慢) / ffmpeg=快速(效果一般)', 'select', '["moviepy","ffmpeg"]', 9),
    ('video', 'default_fade_transition', 'true', '默认淡入淡出', '新建视频任务时的默认值', 'select', '["true","false"]', 10),
    ('video', 'default_title_overlay', 'false', '默认显示标题', '新建视频任务时的默认值', 'select', '["true","false"]', 11),

    # ---- Publish: Douyin ----
    ('publish_douyin', 'enabled', 'true', '启用抖音发布',
     '推荐：复制文案并打开官方创作者页，由你在平台手动点发布（避免自动化封号）',
     'select', '["true","false"]', 1),
    ('publish_douyin', 'cookies', '', '抖音发布 Cookies（可选·高风险）',
     '仅「浏览器自动填充」高级模式需要；登录自动化有封号风险，可不填', 'textarea', None, 2),

    # ---- Publish: Xiaohongshu ----
    ('publish_xiaohongshu', 'enabled', 'true', '启用小红书发布',
     '推荐：复制文案并打开官方创作者页，手动点发布', 'select', '["true","false"]', 1),
    ('publish_xiaohongshu', 'cookies', '', '小红书发布 Cookies（可选·高风险）',
     '仅高级自动填充需要；可不填', 'textarea', None, 2),

    # ---- Publish: Shipinhao ----
    ('publish_shipinhao', 'enabled', 'true', '启用视频号发布',
     '推荐：复制文案并打开官方创作者页，手动点发布', 'select', '["true","false"]', 1),
    ('publish_shipinhao', 'cookies', '', '视频号发布 Cookies（可选·高风险）',
     '仅高级自动填充需要；可不填', 'textarea', None, 2),

    # ---- Publish: 通用 ----
    ('publish', 'keep_open_minutes', '60', '发布浏览器保持打开(分钟)',
     '仅高级「浏览器自动填充」模式使用；安全模式下无需', 'text', None, 1),
    ('publish', 'mode', 'manual', '发布模式',
     'manual=复制文案+打开官方页（推荐）/ autofill=Playwright自动填充（高风险）',
     'select', '["manual","autofill"]', 2),

    # ---- System ----
    ('system', 'collect_interval', '60', '采集间隔(分钟)', '预留：平台口播定时采集间隔（默认已关闭平台采集）', 'text', None, 1),
    ('system', 'auto_publish', 'false', '自动发布', '不推荐开启：自动发布易触发风控', 'select', '["true","false"]', 2),
    # V1.2: Content schedule
    ('system', 'daily_traffic_count', '2', '每日泛流量文案数', '提高播放/点赞/转发/关注', 'text', None, 3),
    ('system', 'daily_insurance_count', '1', '每日保险知识文案数', '保险避坑/理赔案例/家庭保障', 'text', None, 4),
    ('system', 'fixed_ending', '祁实说实话，替你的保单说话，给你最放心的选择。关注我，来找我。', '固定收尾文案', '所有文案统一加入的收尾，形成品牌IP', 'textarea', None, 5),
    ('system', 'daily_auto_enabled', 'false', '每日自动日更', '开启后按设定整点自动：采热点→写文案→出片', 'select', '["true","false"]', 6),
    ('system', 'daily_run_hour', '8', '日更执行整点', '0-23，例如 8 表示每天 8:00-8:10 窗口执行', 'text', None, 7),
    ('system', 'daily_last_run', '', '上次日更时间', '系统自动写入，勿手改', 'text', None, 8),
    ('system', 'daily_last_run_date', '', '上次日更日期', '系统自动写入，用于防同日重复', 'text', None, 9),
    ('system', 'stock_briefing_auto', 'false', '早间自动获取财经新闻',
     '开启后按整点抓取财经资讯并推送到「内容情报 · 股票」页面，可再手动做 AI 总结', 'select', '["true","false"]', 10),
    ('system', 'stock_briefing_hour', '8', '财经新闻获取整点',
     '0-23；整点后约 10 分钟窗口执行，把新闻推送到股票情报页', 'text', None, 11),
    ('system', 'stock_briefing_last_run', '', '上次获取财经新闻时间', '系统自动写入，勿手改', 'text', None, 12),
    ('system', 'stock_briefing_last_date', '', '上次获取财经新闻日期', '系统自动写入，防同日重复', 'text', None, 13),

    # ---- Stock screening ----
    ('stock', 'max_stocks', '300', '初筛扫描上限', '0=全市场(很慢)；建议先 200~500，缓存热了再加大', 'text', None, 1),
    ('stock', 'match_mode', 'and', '默认匹配模式', 'or=命中任一 / and=全部命中 / min=至少N条', 'select',
     '["or","and","min"]', 2),
    ('stock', 'min_hits', '1', '最少命中规则数', '配合 match_mode=min 或 or 使用', 'text', None, 3),
    ('stock', 'pattern_rules_json', '', '自定义形态规则JSON', '留空则用系统默认启用规则', 'textarea', None, 4),
    ('stock', 'cache_dir', '', '行情缓存目录', '留空=backend/data/stock_cache', 'text', None, 5),
    ('stock', 'universe_auto_refresh', 'true', '全市场夜间同步',
     '交易日晚上自动拉取全部 A 股并入库，新股会自动加入', 'select', '["true","false"]', 6),
    ('stock', 'universe_refresh_hour', '18', '全市场同步整点',
     '0-23，默认 18（收盘后）；窗口为该小时前 25 分钟', 'text', None, 7),
    ('stock', 'universe_last_refresh_date', '', '全市场上次同步日期', '系统自动写入', 'text', None, 8),
    ('stock', 'universe_last_refresh_at', '', '全市场上次同步时间', '系统自动写入', 'text', None, 9),
    ('stock', 'watchlist_auto_refresh', 'true', '自选股收盘刷新',
     '交易日收盘后自动刷新自选现价并检查预警', 'select', '["true","false"]', 10),
    ('stock', 'watchlist_refresh_hour', '15', '自选股刷新整点',
     '0-23，默认 15（收盘后）', 'text', None, 11),
    ('stock', 'watchlist_last_refresh_date', '', '自选股上次刷新日期', '系统自动写入', 'text', None, 12),

    # ---- 消息推送（按渠道分卡片，对齐采集平台）----
    ('notify_wecom', 'enabled', 'false', '启用企业微信推送',
     '开启后作为推送渠道；建议只开一个渠道', 'select', '["true","false"]', 1),
    ('notify_wecom', 'webhook', '', '群机器人 Webhook',
     '企微建群 → 添加群机器人 → 复制 Webhook 完整地址', 'textarea', None, 2),

    ('notify_pushplus', 'enabled', 'false', '启用 PushPlus',
     '开启后作为推送渠道；实名可能收费，作备用即可', 'select', '["true","false"]', 1),
    ('notify_pushplus', 'token', '', 'PushPlus Token',
     'pushplus.plus 登录后复制', 'password', None, 2),

    ('notify_serverchan', 'enabled', 'false', '启用 Server酱',
     '开启后作为推送渠道', 'select', '["true","false"]', 1),
    ('notify_serverchan', 'sendkey', '', 'Server酱 SendKey',
     'sct.ftqq.com 登录后复制（SCT 开头）', 'password', None, 2),

    ('notify', 'on_stock_alert', 'true', '股价预警时推送',
     '跌破成本 / 触及目标价时推送', 'select', '["true","false"]', 1),
    ('notify', 'on_screening_done', 'false', '筛选完成时推送',
     '技术面筛选任务完成时推送（可选）', 'select', '["true","false"]', 2),

    # ---- 微信服务号（阶段①：对外 H5 + 留资）----
    ('wechat_oa', 'enabled', 'false', '启用服务号对外页',
     '关闭后客户打开 H5 会提示暂未开放', 'select', '["true","false"]', 1),
    ('wechat_oa', 'brand_name', '祁实说实话', '对外品牌名', '客户页顶部展示', 'text', None, 2),
    ('wechat_oa', 'public_base_url', '', '对外访问地址',
     '客户手机能打开的根地址，如 https://your.domain.com 或 http://公网IP:端口；用于生成菜单链接',
     'text', None, 3),
    ('wechat_oa', 'intro_title', '你好，我是祁实说实话', '介绍页标题', '', 'text', None, 4),
    ('wechat_oa', 'intro_text',
     '替你的保单说话，给你最放心的选择。关注我，来找我。\n可预约一对一沟通，聊聊家庭保障与保单问题。',
     '介绍正文', '支持换行', 'textarea', None, 5),
    ('wechat_oa', 'contact_wechat', '', '对外微信号', '介绍页展示，方便客户添加', 'text', None, 6),
    ('wechat_oa', 'contact_phone', '', '对外电话（可选）', '', 'text', None, 7),
    ('wechat_oa', 'booking_hint', '留下联系方式，我会尽快与你联系。', '预约页提示语', '', 'text', None, 8),
    ('wechat_oa', 'app_id', '', '服务号 AppID（可选）', '阶段②模板消息再用，现在可先填', 'text', None, 9),

    # ---- 官方/商业数据台（API 配置，不爬登录页）----
    # 巨量算数
    ('commercial_julang', 'enabled', 'false', '启用巨量算数',
     '填入你购买/申请的官方或合规代理 API 后拉取榜单；勿用 Cookie 爬网页',
     'select', '["true","false"]', 1),
    ('commercial_julang', 'api_base_url', '', 'API Base URL',
     '如 https://your-gateway.example.com', 'text', None, 2),
    ('commercial_julang', 'api_key', '', 'API Key / Token', '鉴权密钥', 'password', None, 3),
    ('commercial_julang', 'api_secret', '', 'API Secret（可选）', '部分签名接口需要', 'password', None, 4),
    ('commercial_julang', 'endpoint_path', '/hot/rank', '榜单接口路径',
     '相对 Base URL；也可填完整 https URL', 'text', None, 5),
    ('commercial_julang', 'http_method', 'GET', '请求方法', '', 'select', '["GET","POST"]', 6),
    ('commercial_julang', 'auth_type', 'bearer', '鉴权方式',
     'bearer=Authorization Bearer / header=自定义头 / query=URL参数 / none=无',
     'select', '["bearer","header","query","none"]', 7),
    ('commercial_julang', 'auth_header_name', 'X-Api-Key', '鉴权头/参数名',
     'auth_type=header 或 query 时使用', 'text', None, 8),
    ('commercial_julang', 'list_json_path', 'data', '列表 JSON 路径',
     '点分路径，如 data / data.list / result.items', 'text', None, 9),
    ('commercial_julang', 'title_field', 'title,name,word,keyword', '标题字段',
     '逗号分隔候选字段名', 'text', None, 10),
    ('commercial_julang', 'hot_field', 'hot,hot_value,hotValue,score,index', '热度字段',
     '逗号分隔候选', 'text', None, 11),
    ('commercial_julang', 'url_field', 'url,link,rawUrl', '链接字段', '逗号分隔候选', 'text', None, 12),
    ('commercial_julang', 'query_params', '', 'Query 参数 JSON', '如 {"limit":30}', 'textarea', None, 13),
    ('commercial_julang', 'request_body', '', 'POST Body JSON',
     '仅 POST；可用 {{api_key}} 占位', 'textarea', None, 14),
    ('commercial_julang', 'extra_headers', '', '额外请求头 JSON', '如 {"X-Tenant":"xxx"}', 'textarea', None, 15),
    ('commercial_julang', 'limit', '30', '最多条数', '', 'text', None, 16),

    # 蝉妈妈
    ('commercial_chanmama', 'enabled', 'false', '启用蝉妈妈',
     '企业开通的数据 API 或合规网关；配置后拉取热榜/达人榜等',
     'select', '["true","false"]', 1),
    ('commercial_chanmama', 'api_base_url', '', 'API Base URL', '', 'text', None, 2),
    ('commercial_chanmama', 'api_key', '', 'API Key / Token', '', 'password', None, 3),
    ('commercial_chanmama', 'api_secret', '', 'API Secret（可选）', '', 'password', None, 4),
    ('commercial_chanmama', 'endpoint_path', '/hot/rank', '榜单接口路径', '', 'text', None, 5),
    ('commercial_chanmama', 'http_method', 'GET', '请求方法', '', 'select', '["GET","POST"]', 6),
    ('commercial_chanmama', 'auth_type', 'bearer', '鉴权方式', '',
     'select', '["bearer","header","query","none"]', 7),
    ('commercial_chanmama', 'auth_header_name', 'X-Api-Key', '鉴权头/参数名', '', 'text', None, 8),
    ('commercial_chanmama', 'list_json_path', 'data', '列表 JSON 路径', '', 'text', None, 9),
    ('commercial_chanmama', 'title_field', 'title,name,word,keyword', '标题字段', '', 'text', None, 10),
    ('commercial_chanmama', 'hot_field', 'hot,hot_value,hotValue,score,index', '热度字段', '', 'text', None, 11),
    ('commercial_chanmama', 'url_field', 'url,link,rawUrl', '链接字段', '', 'text', None, 12),
    ('commercial_chanmama', 'query_params', '', 'Query 参数 JSON', '', 'textarea', None, 13),
    ('commercial_chanmama', 'request_body', '', 'POST Body JSON', '', 'textarea', None, 14),
    ('commercial_chanmama', 'extra_headers', '', '额外请求头 JSON', '', 'textarea', None, 15),
    ('commercial_chanmama', 'limit', '30', '最多条数', '', 'text', None, 16),

    # 新榜
    ('commercial_xinbang', 'enabled', 'false', '启用新榜',
     '新榜企业 API 或代理网关；配置 Key 后拉取内容榜/热点',
     'select', '["true","false"]', 1),
    ('commercial_xinbang', 'api_base_url', '', 'API Base URL',
     '如官方企业接口域名', 'text', None, 2),
    ('commercial_xinbang', 'api_key', '', 'API Key / Token', '', 'password', None, 3),
    ('commercial_xinbang', 'api_secret', '', 'API Secret（可选）', '', 'password', None, 4),
    ('commercial_xinbang', 'endpoint_path', '/hot/rank', '榜单接口路径', '', 'text', None, 5),
    ('commercial_xinbang', 'http_method', 'GET', '请求方法', '', 'select', '["GET","POST"]', 6),
    ('commercial_xinbang', 'auth_type', 'header', '鉴权方式', '',
     'select', '["bearer","header","query","none"]', 7),
    ('commercial_xinbang', 'auth_header_name', 'Key', '鉴权头/参数名',
     '按厂商文档填写，常见 Key / X-Api-Key', 'text', None, 8),
    ('commercial_xinbang', 'list_json_path', 'data', '列表 JSON 路径', '', 'text', None, 9),
    ('commercial_xinbang', 'title_field', 'title,name,word,keyword', '标题字段', '', 'text', None, 10),
    ('commercial_xinbang', 'hot_field', 'hot,hot_value,hotValue,score,index', '热度字段', '', 'text', None, 11),
    ('commercial_xinbang', 'url_field', 'url,link,rawUrl', '链接字段', '', 'text', None, 12),
    ('commercial_xinbang', 'query_params', '', 'Query 参数 JSON', '', 'textarea', None, 13),
    ('commercial_xinbang', 'request_body', '', 'POST Body JSON', '', 'textarea', None, 14),
    ('commercial_xinbang', 'extra_headers', '', '额外请求头 JSON', '', 'textarea', None, 15),
    ('commercial_xinbang', 'limit', '30', '最多条数', '', 'text', None, 16),

    # 自定义
    ('commercial_custom', 'enabled', 'false', '启用自定义数据源',
     '飞瓜/卡思/自建网关等：只要返回 JSON 列表即可',
     'select', '["true","false"]', 1),
    ('commercial_custom', 'api_base_url', '', 'API Base URL', '', 'text', None, 2),
    ('commercial_custom', 'api_key', '', 'API Key / Token', '', 'password', None, 3),
    ('commercial_custom', 'api_secret', '', 'API Secret（可选）', '', 'password', None, 4),
    ('commercial_custom', 'endpoint_path', '/hot/rank', '榜单接口路径', '', 'text', None, 5),
    ('commercial_custom', 'http_method', 'GET', '请求方法', '', 'select', '["GET","POST"]', 6),
    ('commercial_custom', 'auth_type', 'bearer', '鉴权方式', '',
     'select', '["bearer","header","query","none"]', 7),
    ('commercial_custom', 'auth_header_name', 'Authorization', '鉴权头/参数名', '', 'text', None, 8),
    ('commercial_custom', 'list_json_path', 'data', '列表 JSON 路径', '', 'text', None, 9),
    ('commercial_custom', 'title_field', 'title,name,word,keyword', '标题字段', '', 'text', None, 10),
    ('commercial_custom', 'hot_field', 'hot,hot_value,hotValue,score,index', '热度字段', '', 'text', None, 11),
    ('commercial_custom', 'url_field', 'url,link,rawUrl', '链接字段', '', 'text', None, 12),
    ('commercial_custom', 'query_params', '', 'Query 参数 JSON', '', 'textarea', None, 13),
    ('commercial_custom', 'request_body', '', 'POST Body JSON', '', 'textarea', None, 14),
    ('commercial_custom', 'extra_headers', '', '额外请求头 JSON', '', 'textarea', None, 15),
    ('commercial_custom', 'limit', '30', '最多条数', '', 'text', None, 16),
]


def _add_column_if_not_exists(cur, table, column, col_type):
    """Add a column to a table if it doesn't already exist (PostgreSQL)."""
    cur.execute("""
        SELECT 1 FROM information_schema.columns
        WHERE table_name=%s AND column_name=%s
    """, (table, column))
    if not cur.fetchone():
        cur.execute(f'ALTER TABLE {table} ADD COLUMN {column} {col_type}')
        print(f'  [migration] +{table}.{column} ({col_type})')


def init_db():
    conn = psycopg2.connect(
        host=PG_HOST, port=PG_PORT, dbname=PG_DBNAME,
        user=PG_USER, password=PG_PASSWORD,
    )
    conn.autocommit = True

    # Create all tables
    cur = conn.cursor()
    cur.execute(SCHEMA)

    # Insert default settings (ON CONFLICT DO NOTHING = INSERT OR IGNORE equivalent)
    for item in DEFAULT_SETTINGS:
        cur.execute(
            '''INSERT INTO system_setting
               (category, key, value, label, description, field_type, options, sort_order)
               VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
               ON CONFLICT (category, key) DO NOTHING''',
            item
        )

    # ---- Column migrations for V1.2 lifecycle enhancements ----
    print('[DB] Running column migrations...')
    # customer: ownership & deal tracking
    _add_column_if_not_exists(cur, 'customer', 'owner', "TEXT DEFAULT ''")
    _add_column_if_not_exists(cur, 'customer', 'deal_date', 'DATE')
    _add_column_if_not_exists(cur, 'customer', 'deal_amount', "TEXT DEFAULT ''")
    _add_column_if_not_exists(cur, 'customer', 'policy_type', "TEXT DEFAULT ''")
    _add_column_if_not_exists(cur, 'customer', 'stage_entered_at', 'TIMESTAMP DEFAULT CURRENT_TIMESTAMP')
    # follow_record: stage & result
    _add_column_if_not_exists(cur, 'follow_record', 'follow_stage', "TEXT DEFAULT ''")
    _add_column_if_not_exists(cur, 'follow_record', 'follow_result', "TEXT DEFAULT ''")
    _add_column_if_not_exists(cur, 'follow_record', 'operator', "TEXT DEFAULT ''")
    # reminder: priority & suggested action
    _add_column_if_not_exists(cur, 'reminder', 'priority', "TEXT DEFAULT 'normal'")
    _add_column_if_not_exists(cur, 'reminder', 'suggested_action', "TEXT DEFAULT ''")
    # workflow: link to customer
    _add_column_if_not_exists(cur, 'workflow', 'customer_id', 'INTEGER')
    # ai_agent: 系统提示词（纯文本，不再要求用户填 JSON）
    _add_column_if_not_exists(cur, 'ai_agent', 'system_prompt', "TEXT DEFAULT ''")
    _add_column_if_not_exists(cur, 'ai_agent', 'last_result', "TEXT DEFAULT ''")
    # script: content ops classification
    _add_column_if_not_exists(cur, 'script', 'content_type', "TEXT DEFAULT 'traffic'")
    _add_column_if_not_exists(cur, 'script', 'age_band', "TEXT DEFAULT 'all'")
    # hot_topic: 内容情报字段
    _add_column_if_not_exists(cur, 'hot_topic', 'age_band', "TEXT DEFAULT 'all'")
    _add_column_if_not_exists(cur, 'hot_topic', 'source_type', "TEXT DEFAULT 'platform'")
    _add_column_if_not_exists(cur, 'hot_topic', 'content_kind', "TEXT DEFAULT 'koubo'")
    _add_column_if_not_exists(cur, 'hot_topic', 'engagement_rate', 'REAL DEFAULT 0')
    _add_column_if_not_exists(cur, 'hot_topic', 'engagement_score', 'REAL DEFAULT 0')
    _add_column_if_not_exists(cur, 'stock_screening', 'message', "TEXT DEFAULT ''")
    _add_column_if_not_exists(cur, 'knowledge_item', 'stock_code', "TEXT DEFAULT ''")
    _add_column_if_not_exists(cur, 'publish_task', 'published_at', 'TIMESTAMP')
    _add_column_if_not_exists(cur, 'publish_task', 'got_consult', 'BOOLEAN DEFAULT FALSE')
    _add_column_if_not_exists(cur, 'publish_task', 'likes', 'INTEGER DEFAULT 0')
    _add_column_if_not_exists(cur, 'publish_task', 'comments', 'INTEGER DEFAULT 0')
    _add_column_if_not_exists(cur, 'publish_task', 'session_id', "TEXT DEFAULT ''")
    _add_column_if_not_exists(cur, 'publish_task', 'engagement_synced_at', 'TIMESTAMP')
    _add_column_if_not_exists(cur, 'stock_watchlist', 'target_price', 'REAL DEFAULT 0')
    _add_column_if_not_exists(cur, 'stock_watchlist', 'alert_below_cost', 'BOOLEAN DEFAULT TRUE')
    _add_column_if_not_exists(cur, 'stock_watchlist', 'alert_on_target', 'BOOLEAN DEFAULT TRUE')
    _add_column_if_not_exists(cur, 'video_material', 'asset_kind', "TEXT DEFAULT 'scene'")
    _add_column_if_not_exists(cur, 'video_material', 'style_key', "TEXT DEFAULT ''")
    _add_column_if_not_exists(cur, 'video_task', 'compose_layout', "TEXT DEFAULT 'default'")
    _add_column_if_not_exists(cur, 'video_task', 'person_material_id', 'INTEGER')
    _add_column_if_not_exists(cur, 'video_task', 'bg_material_id', 'INTEGER')
    _add_column_if_not_exists(cur, 'video_task', 'compose_started_at', 'TIMESTAMP')
    _add_column_if_not_exists(cur, 'video_task', 'compose_elapsed_sec', 'REAL DEFAULT 0')
    _add_column_if_not_exists(cur, 'knowledge_item', 'source_file', "TEXT DEFAULT ''")

    # 强制校正品牌内容运营关键设置（修正旧默认值）
    _upsert_setting(cur, 'system', 'fixed_ending',
                    '祁实说实话，替你的保单说话，给你最放心的选择。关注我，来找我。')
    _upsert_setting(cur, 'video', 'default_title_overlay', 'false')

    # 股票情报：更新文案，去掉微信推送开关
    for item in DEFAULT_SETTINGS:
        if str(item[0]) != 'system' or not str(item[1]).startswith('stock_briefing_'):
            continue
        cat, key, _val, label, desc, field_type, options, sort_order = item
        cur.execute(
            '''UPDATE system_setting
               SET label=%s, description=%s, field_type=%s, options=%s, sort_order=%s
               WHERE category=%s AND key=%s''',
            (label, desc, field_type, options, sort_order, cat, key),
        )
    cur.execute(
        'DELETE FROM system_setting WHERE category=%s AND key=%s',
        ('system', 'stock_briefing_push'),
    )
    _upsert_setting(cur, 'ai', 'default_audience',
                    '20-80岁泛流量用户，口播易懂，强共鸣强分享，适合视频号/抖音/小红书')
    _upsert_setting(cur, 'ai', 'default_tone', 'casual')

    # AI 大模型：旧单表 → 分厂商卡片
    def _ai_get(cat, key):
        cur.execute(
            'SELECT value FROM system_setting WHERE category=%s AND key=%s',
            (cat, key),
        )
        row = cur.fetchone()
        return (row[0] if row else '') or ''

    old_provider = (_ai_get('ai', 'provider') or 'zhipu').strip().lower()
    if old_provider in ('volcengine', 'doubao', 'ark', 'huoshan'):
        old_provider = 'volcano'
    old_key = _ai_get('ai', 'api_key')
    old_url = _ai_get('ai', 'base_url')
    old_model = _ai_get('ai', 'model')
    any_ai_on = False
    for pkey in ('zhipu', 'volcano', 'qwen', 'deepseek', 'moonshot', 'openai'):
        if str(_ai_get(f'ai_{pkey}', 'enabled')).lower() == 'true':
            any_ai_on = True
            break
    target_cat = f'ai_{old_provider}' if old_provider in (
        'zhipu', 'volcano', 'qwen', 'deepseek', 'moonshot', 'openai',
    ) else 'ai_zhipu'
    if old_key and not _ai_get(target_cat, 'api_key'):
        _upsert_setting(cur, target_cat, 'api_key', old_key)
    if old_url and not _ai_get(target_cat, 'base_url'):
        _upsert_setting(cur, target_cat, 'base_url', old_url)
    if old_model and not _ai_get(target_cat, 'model'):
        _upsert_setting(cur, target_cat, 'model', old_model)
    if old_key and not any_ai_on:
        _upsert_setting(cur, target_cat, 'enabled', 'true')

    for obsolete_key in ('provider', 'api_key', 'base_url', 'model'):
        cur.execute(
            'DELETE FROM system_setting WHERE category=%s AND key=%s',
            ('ai', obsolete_key),
        )

    # 同步各厂商卡片文案
    for item in DEFAULT_SETTINGS:
        if not (str(item[0]) == 'ai' or str(item[0]).startswith('ai_')):
            continue
        cat, key, _val, label, desc, field_type, options, sort_order = item
        cur.execute(
            '''UPDATE system_setting
               SET label=%s, description=%s, field_type=%s, options=%s, sort_order=%s
               WHERE category=%s AND key=%s''',
            (label, desc, field_type, options, sort_order, cat, key),
        )

    # 仅当仍是旧 AI 副业关键词时才覆盖
    for cat, new_kw in [
        ('collector_douyin', '养老金,家庭保障,保险避坑,理赔案例,职场内耗,育儿焦虑,健康养生,中年危机,防骗防坑,人情世故'),
        ('collector_xiaohongshu', '家庭保障,保险避坑,宝妈理财,重疾险,医保报销,情感共鸣,生活智慧'),
        ('collector_shipinhao', '养老金,保险避坑,理赔,家庭责任,健康预警,退休生活'),
    ]:
        cur.execute('SELECT value FROM system_setting WHERE category=%s AND key=%s', (cat, 'keywords'))
        row = cur.fetchone()
        if row and ('AI副业' in (row[0] or '') or 'AI赚钱' in (row[0] or '') or 'AI工具' in (row[0] or '')):
            _upsert_setting(cur, cat, 'keywords', new_kw)

    # 安全策略：默认关闭平台登录态采集（易封号）；发布改为启用（人工复制+打开官方页）
    for cat in ('collector_douyin', 'collector_xiaohongshu', 'collector_shipinhao'):
        _upsert_setting(cur, cat, 'enabled', 'false')
    for cat in ('publish_douyin', 'publish_xiaohongshu', 'publish_shipinhao'):
        # 仅当从未启用过时不强制改用户选择；但若仍是旧默认 false，升为 true 以支持安全发布
        cur.execute('SELECT value FROM system_setting WHERE category=%s AND key=%s', (cat, 'enabled'))
        row = cur.fetchone()
        if row is None or str(row[0] or '').lower() in ('', 'false'):
            _upsert_setting(cur, cat, 'enabled', 'true')
    _upsert_setting(cur, 'publish', 'mode', 'manual')
    _upsert_setting(cur, 'system', 'auto_publish', 'false')

    # 消息推送：旧版单表 notify → 分渠道卡片；同步文案
    for item in DEFAULT_SETTINGS:
        if not str(item[0]).startswith('notify'):
            continue
        cat, key, _val, label, desc, field_type, options, sort_order = item
        cur.execute(
            '''UPDATE system_setting
               SET label=%s, description=%s, field_type=%s, options=%s, sort_order=%s
               WHERE category=%s AND key=%s''',
            (label, desc, field_type, options, sort_order, cat, key),
        )

    def _get_setting_val(category, key):
        cur.execute(
            'SELECT value FROM system_setting WHERE category=%s AND key=%s',
            (category, key),
        )
        row = cur.fetchone()
        return (row[0] if row else '') or ''

    # 迁移旧字段到分渠道（仅当新字段仍为空时）
    old_hook = _get_setting_val('notify', 'wecom_webhook')
    old_token = _get_setting_val('notify', 'pushplus_token')
    old_sct = _get_setting_val('notify', 'serverchan_sendkey')
    old_enabled = str(_get_setting_val('notify', 'enabled')).lower() == 'true'
    old_provider = (_get_setting_val('notify', 'provider') or 'wecom').strip().lower()

    if old_hook and not _get_setting_val('notify_wecom', 'webhook'):
        _upsert_setting(cur, 'notify_wecom', 'webhook', old_hook)
    if old_token and not _get_setting_val('notify_pushplus', 'token'):
        _upsert_setting(cur, 'notify_pushplus', 'token', old_token)
    if old_sct and not _get_setting_val('notify_serverchan', 'sendkey'):
        _upsert_setting(cur, 'notify_serverchan', 'sendkey', old_sct)

    any_channel_on = any(
        str(_get_setting_val(c, 'enabled')).lower() == 'true'
        for c in ('notify_wecom', 'notify_pushplus', 'notify_serverchan')
    )
    if old_enabled and not any_channel_on:
        target = {
            'wecom': 'notify_wecom',
            'pushplus': 'notify_pushplus',
            'serverchan': 'notify_serverchan',
        }.get(old_provider, 'notify_wecom')
        _upsert_setting(cur, target, 'enabled', 'true')

    # 推送规则卡片只保留事件开关，删掉已迁走的旧字段
    for obsolete_key in (
        'enabled', 'provider', 'wecom_webhook', 'pushplus_token', 'serverchan_sendkey',
    ):
        cur.execute(
            'DELETE FROM system_setting WHERE category=%s AND key=%s',
            ('notify', obsolete_key),
        )

    # Edge TTS 大量中文音色已下线：更新下拉选项，并把已失效音色映射到仍可用的
    _alive_voices = [
        'zh-CN-YunxiNeural', 'zh-CN-XiaoxiaoNeural', 'zh-CN-YunyangNeural',
        'zh-CN-XiaoyiNeural', 'zh-CN-YunjianNeural', 'zh-CN-YunxiaNeural',
        'zh-CN-liaoning-XiaobeiNeural', 'zh-CN-shaanxi-XiaoniNeural',
    ]
    import json as _json
    cur.execute(
        '''UPDATE system_setting SET options=%s, description=%s
           WHERE category=%s AND key=%s''',
        (
            _json.dumps(_alive_voices, ensure_ascii=False),
            '可在创建视频时单独选择，也可在此设置全局默认（仅列出 Edge TTS 仍可用的音色）',
            'tts', 'voice',
        ),
    )
    _voice_remap = {
        'zh-CN-XiaoqiuNeural': 'zh-CN-XiaoxiaoNeural',
        'zh-CN-XiaochenNeural': 'zh-CN-XiaoxiaoNeural',
        'zh-CN-XiaohanNeural': 'zh-CN-XiaoxiaoNeural',
        'zh-CN-XiaomengNeural': 'zh-CN-XiaoyiNeural',
        'zh-CN-XiaomoNeural': 'zh-CN-XiaoyiNeural',
        'zh-CN-XiaoruiNeural': 'zh-CN-XiaoxiaoNeural',
        'zh-CN-XiaoshuangNeural': 'zh-CN-XiaoyiNeural',
        'zh-CN-XiaoxuanNeural': 'zh-CN-XiaoyiNeural',
        'zh-CN-XiaoyanNeural': 'zh-CN-XiaoxiaoNeural',
        'zh-CN-XiaozhenNeural': 'zh-CN-XiaoxiaoNeural',
        'zh-CN-YunfengNeural': 'zh-CN-YunxiNeural',
        'zh-CN-YunhaoNeural': 'zh-CN-YunyangNeural',
        'zh-CN-YunzeNeural': 'zh-CN-YunjianNeural',
    }
    for old, new in _voice_remap.items():
        cur.execute(
            'UPDATE system_setting SET value=%s WHERE category=%s AND key=%s AND value=%s',
            (new, 'tts', 'voice', old),
        )
        cur.execute(
            'UPDATE system_setting SET value=%s WHERE category=%s AND key=%s AND value=%s',
            (new, 'video_prefs', 'last_voice', old),
        )
        cur.execute(
            '''UPDATE video_task SET voice=%s
               WHERE voice=%s AND COALESCE(export_status,'') != 'done' ''',
            (new, old),
        )

    conn.commit()
    conn.close()
    print(f'[DB] PostgreSQL initialized: {PG_HOST}:{PG_PORT}/{PG_DBNAME}')

    try:
        from modules.ai.providers import ensure_builtin_settings
        ensure_builtin_settings()
        print('[DB] AI LLM provider settings ensured')
    except Exception as e:
        print(f'[DB] Warning: ensure AI settings failed: {e}')


def _upsert_setting(cur, category, key, value):
    cur.execute(
        '''INSERT INTO system_setting (category, key, value, description, field_type, options)
           VALUES (%s, %s, %s, '', 'text', NULL)
           ON CONFLICT (category, key) DO UPDATE SET value = EXCLUDED.value''',
        (category, key, value)
    )


if __name__ == '__main__':
    init_db()
